apiVersion: newrelic.com/v1beta3
kind: Instrumentation
metadata:
  name: newrelic-java
  namespace: default
spec:
  agent:
    language: java
    image: newrelic/newrelic-java-init:latest
  licenseKeySecret: newrelic-key-secret
