apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-config
data:
  NEW_RELIC_APP_NAME: "dotnet-api"
  NEW_RELIC_LOG_LEVEL: "info"
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
