apiVersion: newrelic.com/v1alpha2
kind: Instrumentation
metadata:
  name: newrelic-dotnet
spec:
  dotnet:
    image: newrelic/newrelic-dotnet-init:latest
  env:
    - name: NEW_RELIC_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: newrelic-secret
          key: license-key
