apiVersion: newrelic.com/v1beta3
kind: Instrumentation
metadata:
  name: newrelic-dotnet
  namespace: default
spec:
  agent:
    language: dotnet
    image: newrelic/newrelic-dotnet-init:latest
  licenseKeySecret: newrelic-key-secret
