apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secret
  namespace: springboot
type: Opaque
stringData:
  # Replace with your actual values before applying
  license-key: "<INGEST-LICENSE-API-KEY>"
  account-id: "<ACCOUNT-ID>"